export const activitiesSeed = [
  {
    id: "activity-1",
    userId: "emp-1",
    userType: "employer",
    entityType: "gig",
    entityId: "gig-1",
    action: "created",
    description: "Posted new gig 'Smart Contract Security Audit'",
    metadata: {
      gigTitle: "Smart Contract Security Audit",
      budget: "5000.00",
      category: "Development",
    },
    createdAt: new Date("2024-10-01"),
  },
  {
    id: "activity-2",
    userId: "worker-1",
    userType: "worker",
    entityType: "application",
    entityId: "app-1",
    action: "submitted",
    description: "Applied to gig 'Smart Contract Security Audit'",
    metadata: {
      gigId: "gig-1",
      gigTitle: "Smart Contract Security Audit",
      proposedRate: "5000.00",
    },
    createdAt: new Date("2024-10-02"),
  },
  {
    id: "activity-3",
    userId: "worker-1",
    userType: "worker",
    entityType: "milestone",
    entityId: "milestone-4",
    action: "completed",
    description: "Completed milestone 'UI Component Development'",
    metadata: {
      gigId: "gig-2",
      gigTitle: "Frontend Developer for DApp",
      amount: "2000.00",
    },
    createdAt: new Date("2024-10-04"),
  },
  {
    id: "activity-4",
    userId: "emp-1",
    userType: "employer",
    entityType: "payment",
    entityId: "payment-1",
    action: "processed",
    description: "Processed payment for milestone 'UI Component Development'",
    metadata: {
      gigId: "gig-2",
      workerId: "worker-1",
      amount: "2000.00",
      currency: "USDC",
    },
    createdAt: new Date("2024-10-05"),
  },
  {
    id: "activity-5",
    userId: "inv-1",
    userType: "investor",
    entityType: "investment",
    entityId: "invest-1",
    action: "invested",
    description: "Invested 5000 USDC in 'Frontend Developer for DApp'",
    metadata: {
      gigId: "gig-2",
      amount: "5000.00",
      expectedReturn: "5225.00",
    },
    createdAt: new Date("2024-09-18"),
  },
  {
    id: "activity-6",
    userId: "inv-2",
    userType: "investor",
    entityType: "deposit",
    entityId: "deposit-2",
    action: "deposited",
    description: "Deposited 15000 USDC into DeFi Gigs Growth Pool",
    metadata: {
      poolId: "pool-1",
      poolName: "DeFi Gigs Growth Pool",
      amount: "15000.00",
    },
    createdAt: new Date("2024-09-15"),
  },
  {
    id: "activity-7",
    userId: "emp-2",
    userType: "employer",
    entityType: "rating",
    entityId: "rating-1",
    action: "submitted",
    description: "Rated worker for 'Technical Documentation Writer'",
    metadata: {
      gigId: "gig-4",
      workerId: "worker-2",
      rating: 5,
    },
    createdAt: new Date("2024-09-16"),
  },
  {
    id: "activity-8",
    userId: "worker-1",
    userType: "worker",
    entityType: "financing",
    entityId: "fin-2",
    action: "approved",
    description: "Financing request approved for 'Frontend Developer for DApp'",
    metadata: {
      gigId: "gig-2",
      amount: "8000.00",
      interestRate: "4.5",
    },
    createdAt: new Date("2024-09-18"),
  },
];
