export const employerNotificationsSeed = [
  {
    id: "emp-notif-1",
    employerId: "emp-1",
    gigId: "gig-2",
    type: "milestone_submitted",
    title: "Milestone Submitted for Review",
    message: "Worker has submitted 'UI Component Development' milestone for your review",
    priority: "high",
    read: true,
    createdAt: new Date("2024-10-04"),
    readAt: new Date("2024-10-04"),
  },
  {
    id: "emp-notif-2",
    employerId: "emp-1",
    gigId: "gig-1",
    type: "payment_processed",
    title: "Payment Processed",
    message: "Escrow payment of 5000 USDC has been successfully deposited for 'Smart Contract Security Audit'",
    priority: "medium",
    read: true,
    createdAt: new Date("2024-10-01"),
    readAt: new Date("2024-10-02"),
  },
  {
    id: "emp-notif-3",
    employerId: "emp-2",
    gigId: "gig-3",
    type: "gig_deadline_approaching",
    title: "Gig Deadline Approaching",
    message: "Your gig 'NFT Smart Contract Development' deadline is in 7 days",
    priority: "medium",
    read: false,
    createdAt: new Date("2024-10-24"),
  },
  {
    id: "emp-notif-4",
    employerId: "emp-1",
    type: "reputation_milestone",
    title: "Reputation Milestone Achieved",
    message: "Congratulations! Your reputation score has reached 95. You've unlocked premium features!",
    priority: "low",
    read: false,
    createdAt: new Date("2024-10-15"),
  },
];
