export const gigNotificationsSeed = [
  {
    id: "notif-1",
    userId: "worker-1",
    userType: "worker",
    gigId: "gig-2",
    type: "milestone_completed",
    title: "Milestone Completed",
    message: "Your milestone 'UI Component Development' has been approved and payment is being processed",
    read: true,
    createdAt: new Date("2024-10-05"),
    readAt: new Date("2024-10-05"),
  },
  {
    id: "notif-2",
    userId: "emp-1",
    userType: "employer",
    gigId: "gig-1",
    type: "new_application",
    title: "New Application Received",
    message: "You have a new application for 'Smart Contract Security Audit'",
    read: true,
    createdAt: new Date("2024-10-02"),
    readAt: new Date("2024-10-03"),
  },
  {
    id: "notif-3",
    userId: "worker-1",
    userType: "worker",
    gigId: "gig-2",
    type: "application_accepted",
    title: "Application Accepted",
    message: "Congratulations! Your application for 'Frontend Developer for DApp' has been accepted",
    read: true,
    createdAt: new Date("2024-09-18"),
    readAt: new Date("2024-09-18"),
  },
  {
    id: "notif-4",
    userId: "worker-1",
    userType: "worker",
    gigId: "gig-2",
    type: "milestone_due_soon",
    title: "Milestone Due Soon",
    message: "Reminder: 'Smart Contract Integration' milestone is due in 3 days",
    read: false,
    createdAt: new Date("2024-10-28"),
  },
  {
    id: "notif-5",
    userId: "emp-2",
    userType: "employer",
    gigId: "gig-3",
    type: "new_application",
    title: "New Application Received",
    message: "You have a new application for 'NFT Smart Contract Development'",
    read: false,
    createdAt: new Date("2024-10-11"),
  },
];
