export const gigMilestonesSeed = [
  {
    id: "milestone-1",
    gigId: "gig-1",
    title: "Initial Analysis and Report",
    description: "Complete initial security analysis and provide preliminary findings report",
    amount: "1666.67",
    order: 1,
    status: "pending",
    dueDate: new Date("2024-11-05"),
    createdAt: new Date("2024-10-01"),
  },
  {
    id: "milestone-2",
    gigId: "gig-1",
    title: "Detailed Vulnerability Assessment",
    description: "Comprehensive vulnerability assessment with proof of concepts",
    amount: "1666.67",
    order: 2,
    status: "pending",
    dueDate: new Date("2024-11-10"),
    createdAt: new Date("2024-10-01"),
  },
  {
    id: "milestone-3",
    gigId: "gig-1",
    title: "Final Audit Report",
    description: "Complete audit report with recommendations and fixes verification",
    amount: "1666.66",
    order: 3,
    status: "pending",
    dueDate: new Date("2024-11-15"),
    createdAt: new Date("2024-10-01"),
  },
  {
    id: "milestone-4",
    gigId: "gig-2",
    title: "UI Component Development",
    description: "Build core UI components with Web3 wallet integration",
    amount: "2000.00",
    order: 1,
    status: "completed",
    dueDate: new Date("2024-10-05"),
    createdAt: new Date("2024-09-15"),
    completedAt: new Date("2024-10-04"),
  },
  {
    id: "milestone-5",
    gigId: "gig-2",
    title: "Smart Contract Integration",
    description: "Integrate smart contracts with frontend using ethers.js",
    amount: "2000.00",
    order: 2,
    status: "in_progress",
    dueDate: new Date("2024-10-19"),
    createdAt: new Date("2024-09-15"),
  },
  {
    id: "milestone-6",
    gigId: "gig-2",
    title: "Responsive Design Implementation",
    description: "Make application fully responsive for mobile and tablet",
    amount: "2000.00",
    order: 3,
    status: "pending",
    dueDate: new Date("2024-11-02"),
    createdAt: new Date("2024-09-15"),
  },
  {
    id: "milestone-7",
    gigId: "gig-2",
    title: "Testing and Deployment",
    description: "Complete testing, bug fixes, and production deployment",
    amount: "2000.00",
    order: 4,
    status: "pending",
    dueDate: new Date("2024-11-16"),
    createdAt: new Date("2024-09-15"),
  },
];
