export const gigsSeed = [
  {
    id: "gig-1",
    employerId: "emp-1",
    title: "Smart Contract Security Audit",
    description: "Need experienced auditor for DeFi protocol smart contracts. Must have experience with Solidity and common vulnerabilities.",
    category: "Development",
    subcategory: "Smart Contracts",
    budget: "5000.00",
    budgetCurrency: "USDC",
    duration: "2 weeks",
    skillsRequired: ["Solidity", "Security Auditing", "DeFi"],
    status: "open",
    applicantsCount: 5,
    milestoneCount: 3,
    createdAt: new Date("2024-10-01"),
    updatedAt: new Date("2024-10-15"),
    deadline: new Date("2024-11-15"),
    requiredCollateral: "500.00",
    financingAvailable: true,
  },
  {
    id: "gig-2",
    employerId: "emp-1",
    title: "Frontend Developer for DApp",
    description: "Build responsive React frontend for our DeFi platform with Web3 integration.",
    category: "Development",
    subcategory: "Frontend",
    budget: "8000.00",
    budgetCurrency: "USDC",
    duration: "4 weeks",
    skillsRequired: ["React", "TypeScript", "Web3", "Ethers.js"],
    status: "in_progress",
    applicantsCount: 12,
    milestoneCount: 4,
    createdAt: new Date("2024-09-15"),
    updatedAt: new Date("2024-10-20"),
    deadline: new Date("2024-11-30"),
    requiredCollateral: "800.00",
    financingAvailable: true,
    selectedWorkerId: "worker-1",
  },
  {
    id: "gig-3",
    employerId: "emp-2",
    title: "NFT Smart Contract Development",
    description: "Create ERC-721 NFT contract with custom minting logic and royalties.",
    category: "Development",
    subcategory: "Smart Contracts",
    budget: "3500.00",
    budgetCurrency: "USDC",
    duration: "3 weeks",
    skillsRequired: ["Solidity", "NFT Standards", "OpenZeppelin"],
    status: "open",
    applicantsCount: 8,
    milestoneCount: 3,
    createdAt: new Date("2024-10-10"),
    updatedAt: new Date("2024-10-25"),
    deadline: new Date("2024-12-01"),
    requiredCollateral: "350.00",
    financingAvailable: false,
  },
  {
    id: "gig-4",
    employerId: "emp-2",
    title: "Technical Documentation Writer",
    description: "Create comprehensive documentation for DeFi protocol including user guides and API docs.",
    category: "Content",
    subcategory: "Technical Writing",
    budget: "2000.00",
    budgetCurrency: "USDC",
    duration: "2 weeks",
    skillsRequired: ["Technical Writing", "DeFi Knowledge", "Documentation"],
    status: "completed",
    applicantsCount: 6,
    milestoneCount: 2,
    createdAt: new Date("2024-08-01"),
    updatedAt: new Date("2024-09-15"),
    deadline: new Date("2024-09-15"),
    requiredCollateral: "200.00",
    financingAvailable: false,
    selectedWorkerId: "worker-2",
    completedAt: new Date("2024-09-15"),
  },
  {
    id: "gig-5",
    employerId: "emp-3",
    title: "UI/UX Design for NFT Platform",
    description: "Design modern and intuitive interface for NFT marketplace with focus on user experience.",
    category: "Design",
    subcategory: "UI/UX",
    budget: "4000.00",
    budgetCurrency: "USDC",
    duration: "3 weeks",
    skillsRequired: ["UI Design", "UX Design", "Figma", "Web3 UX"],
    status: "open",
    applicantsCount: 10,
    milestoneCount: 4,
    createdAt: new Date("2024-10-20"),
    updatedAt: new Date("2024-10-28"),
    deadline: new Date("2024-12-15"),
    requiredCollateral: "400.00",
    financingAvailable: true,
  },
];
