export const investorNotificationsSeed = [
  {
    id: "inv-notif-1",
    investorId: "inv-1",
    investmentId: "invest-1",
    gigId: "gig-2",
    type: "investment_opportunity",
    title: "New Investment Opportunity",
    message: "A new gig matching your criteria is seeking financing: 'Frontend Developer for DApp'",
    priority: "medium",
    read: true,
    createdAt: new Date("2024-09-16"),
    readAt: new Date("2024-09-17"),
  },
  {
    id: "inv-notif-2",
    investorId: "inv-3",
    investmentId: "invest-3",
    gigId: "gig-4",
    type: "return_received",
    title: "Investment Return Received",
    message: "You've received 2080 USDC return on your investment in 'Technical Documentation Writer'",
    priority: "high",
    read: true,
    createdAt: new Date("2024-09-15"),
    readAt: new Date("2024-09-15"),
  },
  {
    id: "inv-notif-3",
    investorId: "inv-1",
    poolId: "pool-1",
    type: "pool_performance",
    title: "Pool Performance Update",
    message: "Your pool 'DeFi Gigs Growth Pool' has earned 425 USDC in returns this month",
    priority: "low",
    read: false,
    createdAt: new Date("2024-10-01"),
  },
  {
    id: "inv-notif-4",
    investorId: "inv-2",
    depositId: "deposit-5",
    type: "lock_period_ended",
    title: "Lock Period Ended",
    message: "Your deposit in 'DeFi Gigs Growth Pool' is now available for withdrawal",
    priority: "medium",
    read: true,
    createdAt: new Date("2024-08-30"),
    readAt: new Date("2024-09-01"),
  },
];
